### ISSUE TITLE
Add support for newer slim-lint

### ISSUE THREAD

**Issue by dimitrovv** [nysthee/pronto-slim#10]
Hi, is it possible to add support for the newest version of slim-lint **0.15.1** or at least **0.14**. 
There are fixes which are not included in version 0.12, used by the most actual version of the pronto-slim 0.5.0

I would highly appreciate it, thanks!

**Comment by nysthee** [comment]
Released a new version: https://rubygems.org/gems/pronto-slim

**Comment by dimitrovv** [comment]
Thanks for the support, appreciated 💯
